In [18]:
import numpy as np 
from sklearn.datasets import load_iris
from sklearn.pipeline import make_pipeline 
from sklearn.preprocessing import StandardScaler 
from sklearn.svm import LinearSVC

In [19]:
iris = load_iris(as_frame=True)
iris.data.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2

In [20]:
X = iris.data[['petal length (cm)','petal width (cm)']].values
y=(iris.target == 2)

In [21]:
len(X),len(y)

(150, 150)

In [23]:
svm_pipeline = make_pipeline(StandardScaler(),LinearSVC(C=1,dual=True,random_state=42))
svm_pipeline.fit(X,y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('linearsvc', LinearSVC(C=1, dual=True, random_state=42))])

In [29]:
x_new= [[5.5,1.7],[5.0,1.5]]
svm_pipeline.predict(x_new)

array([ True, False])

In [30]:
svm_pipeline.decision_function(x_new)

array([ 0.66163411, -0.22036063])

## Non Linear SVM Classification

In [38]:
from sklearn.datasets import make_moons
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import PolynomialFeatures

In [39]:
polynomial_svm_clf = Pipeline([
    ('poly_features',PolynomialFeatures(degree=3)),
    ('scaler',StandardScaler()),
    ('svm_clf',LinearSVC(loss='hinge',C=10))
])

In [40]:
polynomial_svm_clf.fit(X,y)

C:\Users\Diacto\miniconda3\Lib\site-packages\sklearn\svm\_classes.py:31: FutureWarning: The default value of `dual` will change from `True` to `'auto'` in 1.5. Set the value of `dual` explicitly to suppress the warning.
  warnings.warn(


Pipeline(steps=[('poly_features', PolynomialFeatures(degree=3)),
                ('scaler', StandardScaler()),
                ('svm_clf', LinearSVC(C=10, loss='hinge'))])

In [41]:
polynomial_svm_clf.predict(x_new)

array([ True, False])

In [43]:
X,y= make_moons(n_samples=100,noise=0.15,random_state=42)
poynomial_svm = make_pipeline(
    PolynomialFeatures(degree=3),
    StandardScaler(),
    LinearSVC(C=10,max_iter=10_000,dual=True,random_state=42))

In [44]:
poynomial_svm.fit(X,y)

Pipeline(steps=[('polynomialfeatures', PolynomialFeatures(degree=3)),
                ('standardscaler', StandardScaler()),
                ('linearsvc',
                 LinearSVC(C=10, dual=True, max_iter=10000, random_state=42))])

In [46]:
import matplotlib.pyplot as plt

In [ ]:
def plot_dataset(X,y,axes):
    plt.plot(X[:,0][y==0],X[:,1][y==0],'bs')
    plt.plot(X[:,0][y==1],X[:,1][y==1],'g^')
    plt.axis(axes)
    plt.grid(True)
    plt.xlabel("$x_1$")
    plt.ylabel("$x_2$", rotation=0)